---
- name: "Ensure account is absent for user {{ account.name }}"
  ansible.builtin.user:
    name: "{{ account.name }}"
    state: absent
    remove: "{{ account.remove | default(omit) }}"
    force: "{{ account.force | default(omit) }}"
  when: account.name is defined

- name: "Ensure sudo configuration is removed for user {{ account.name }}"
  ansible.builtin.file:
    path: "/etc/sudoers.d/account_{{ account.name }}"
    state: absent
