---
- name: "Ensure private key is available for {{ account.name }}"
  ansible.builtin.include_tasks:
    file: "ssh_keypair_{{ 'present' if _key.state | default('present') == 'present' else 'absent' }}.yml"
  no_log: true
  loop: "{{ account.ssh_keypairs }}"
  loop_control:
    loop_var: _key
    label: "{{ _key.dest }}"
  when:
    - current_user.home is defined
