---
- name: "Include key pair logic for user {{ account.name }}"
  ansible.builtin.include_tasks:
    file: "ssh_keypair_{{ state }}.yml"
  # no_log: true
  loop: "{{ account.ssh_keypairs }}"
  loop_control:
    loop_var: _key
    label: "{{ _key.dest }}"
  when:
    - current_user.home is defined
  vars:
    state: "{{ 'absent' if _key.state | default('present') == 'absent' else 'present' }}"
